name: Publish Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 2 * * 3' # Weekly on Wednesday at 02:30

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua
          tags: "latest,5.4"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 5.4/Dockerfile

  alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua
          tags: "alpine,5.4-alpine"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 5.4/alpine/Dockerfile

  jit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua
          tags: "jit,jit-2.0"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: jit-2.0/Dockerfile

  jit-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build latest version and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua
          tags: "jit-alpine,jit-2.0-alpine"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: jit-2.0/alpine/Dockerfile

  buildGeneral:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["5.3", "5.2", "5.1", "jit-2.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Build Lua ${{ matrix.version }} and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua:${{ matrix.version }}
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/Dockerfile

  buildAlpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["5.3", "5.2", "5.1", "jit-2.1"]
    steps:
      - uses: actions/checkout@v3
      - name: Build Lua ${{ matrix.version }} and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/lua:${{ matrix.version }}-alpine
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/alpine/Dockerfile
